apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "nextjs-app"
  name: "nextjs-app"
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nextjs-app"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "nextjs-app"
    spec:
      containers:
        - image: ghcr.io/ebox86/portfolio-website:latest
          imagePullPolicy: Always
          name: "nextjs-app"
          env:
            - name: "REACT_APP_ENVIRONMENT"
              value: "PROD"
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: 500m     # 0.5 CPU cores
              memory: 512Mi # 512 MiB
            requests:
              cpu: 100m     # 0.1 CPU cores
              memory: 256Mi # 256 MiB
      imagePullSecrets:
        - name: ghcr-pat
      dnsPolicy: ClusterFirst
      restartPolicy: Always
