import type { Metadata } from 'next'
import React from 'react';
import localFont from 'next/font/local';
import Header from '../components/Header';
import Footer from '../components/Footer';

import '../styles/globals.css'

const fira = localFont({
  src: [
    {
      path: '../styles/FiraCode-Light.ttf',
      weight: '300'
    },
    {
      path: '../styles/FiraCode-Regular.ttf',
      weight: '400'
    },
    {
      path: '../styles/FiraCode-Medium.ttf',
      weight: '500'
    },
    {
      path: '../styles/FiraCode-SemiBold.ttf',
      weight: '600'
    },
    {
      path: '../styles/FiraCode-Bold.ttf',
      weight: '700'
    }
  ],
  variable: '--font-fira'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${fira.variable} font-sans`}>
      <div className="flex flex-col min-h-screen bg-gray-100">
        <div className="container mx-auto max-w-screen-md flex-grow">
            <Header />
            <div className='px-4 py-8'>
                {children}
            </div>
        </div>
        <Footer />
    </div>
      </body>
    </html>
  );
}